feat: Check assets in bridges before claim in mainnet
godwokenrises/godwoken-faucet pull request #11
Opened 2023-06-21 03:27 UTC by classicalliu

2023-06-22 06:07 UTC, Flouse requested changes

2023-06-22 06:07 UTC, Flouse commented on src/pages/api/claim.ts
> +        message: `Don't have enough USD in bridges`,
```suggestion
        message: `To stop spam attacks draining the faucet, the account must contain assets such as USDC or USDT that have been bridged from Celer cBridge or Multichain.`
```

2023-06-22 06:07 UTC, Flouse commented on src/pages/api/claim.ts
> +      return res.status(200).json({
Maybe we should use a `40x` code?

2023-06-22 06:07 UTC, Flouse commented on src/lib/bridges/prices/average.ts
> +  if (failedPriceInfos === 0) {
```suggestion
  if (failedPriceInfos === 3) {
```

2023-06-25 03:40 UTC, classicalliu commented on src/pages/api/claim.ts
> +      return res.status(200).json({
Updated to `422`

2023-06-25 03:50 UTC, Flouse approved these changes

2023-06-25 03:50 UTC, merged